

// TOOL:     vlog2tf
// DATE:     Tue Apr 29 19:59:51 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   demux_14
// DESIGN:   demux_14
// FILENAME: demux_14_tf.v
// PROJECT:  demux_18_214
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module demux_14_tf();

// Inputs
    reg in;
    reg [1:0] sel;


// Outputs
    wire [3:0] out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    demux_14 UUT (
        .in(in), 
        .sel(sel), 
        .out(out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            in = 1;
            sel = 2'b00;#10
            sel = 2'b01;#10
            sel = 2'b10;#10
            sel = 2'b11;
    end

endmodule // demux_14_tf