

// TOOL:     vlog2tf
// DATE:     Wed May 07 20:34:51 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   bcd_3bits
// DESIGN:   bcd_3bits
// FILENAME: bcd_3bits_tf.v
// PROJECT:  bcd_1bit
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module bcd_3bits_tf();

// Inputs
    reg [11:0] A;
    reg [11:0] B;
    reg Cin;


// Outputs
    wire Cout;
    wire [11:0] Sum;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    bcd_3bits UUT (
        .A(A), 
        .B(B), 
        .Cin(Cin), 
        .Cout(Cout), 
        .Sum(Sum)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            A = 8'b10011001;
            B = 0;
            Cin = 0;
			#10
			A = 300;
            B = 0;
            Cin = 0;
			#10
			A = 8'b10011000;
            B = 54;
            Cin = 1;
    end

endmodule // bcd_3bits_tf