

// TOOL:     vlog2tf
// DATE:     Wed May 07 20:03:18 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   sum_correction
// DESIGN:   sum_correction
// FILENAME: sum_correction_tf.v
// PROJECT:  bcd_1bit
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module sum_correction_tf();

// Inputs
    reg Cin;
    reg [3:0] A;
    reg [3:0] B;


// Outputs
    wire Cout_out;
    wire [3:0] Sum_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    sum_correction UUT (
        .Cin(Cin), 
        .A(A), 
        .B(B), 
        .Cout_out(Cout_out), 
        .Sum_out(Sum_out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
      Cin = 1'b0;
	  A = 4'b0001;
	  B = 4'b1110;
      #10
	  Cin = 1'b0;
	  A = 4'b0011;
	  B = 4'b0010;
      #10
	  Cin = 1'b1;
	  A = 4'b0001;
	  B = 4'b0010;
      #10
	  Cin = 1'b1;
	  A = 4'b0011;
	  B = 4'b1000;
      
    end

endmodule // sum_correction_tf