

// TOOL:     vlog2tf
// DATE:     Fri Apr 25 20:54:22 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   cod_16_4bits
// DESIGN:   cod_16_4bits
// FILENAME: cod_16_4bits_tf.v
// PROJECT:  cod_16_4
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module cod_16_4bits_tf();

// Inputs
    reg [15:0] a_in;


// Outputs
    wire [3:0] a_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    cod_16_4bits UUT (
        .a_in(a_in), 
        .a_out(a_out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            a_in = 16'b0000000000000001; #10
			a_in = 16'b0000000000000011; #10
			a_in = 16'b0000000000000111; #10
			a_in = 16'b0000000000001111; #10
			a_in = 16'b0000000000010000; #10
			a_in = 16'b0000000000111111; #10
			a_in = 16'b0000000001111111; #10
			a_in = 16'b0000000010001111; #10
			a_in = 16'b0000000111111111; #10
			a_in = 16'b0000001000000111; #10
			a_in = 16'b0000011111111111; #10
			a_in = 16'b0000111111111111; #10
			a_in = 16'b0001111111111111; #10
			a_in = 16'b0010000000001111; #10
			a_in = 16'b0100000000000000; #10
			a_in = 16'b1000000011111111;
    end

endmodule // cod_16_4bits_tf