

// TOOL:     vlog2tf
// DATE:     Thu Apr 24 21:39:59 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   coder_decoder
// DESIGN:   coder_decoder
// FILENAME: coder_decoder_tf.v
// PROJECT:  code_decoder
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 10 ns / 1 ps

// Define Module for Test Fixture
module coder_decoder_tf();

// Inputs
    reg H;
    reg G;
    reg F;
    reg E;


// Outputs
    wire [3:0] Y;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    coder_decoder UUT (
        .H(H), 
        .G(G), 
        .F(F), 
        .E(E), 
        .Y(Y)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            H = 0;
            G = 0;
            F = 0;
            E = 0;
			#5
			H = 0;
            G = 0;
            F = 0;
            E = 1;
			#5
			H = 0;
            G = 0;
            F = 1;
            E = 1;
			#5
			H = 0;
            G = 1;
            F = 0;
            E = 0;
			#5
			H = 0;
            G = 1;
            F = 0;
            E = 1;
			#5
			H = 0;
            G = 1;
            F = 1;
            E = 1;
			#5
			H = 1;
            G = 0;
            F = 0;
            E = 1;
			#5
			H = 1;
            G = 0;
            F = 1;
            E = 1;
			#5
			H = 1;
            G = 1;
            F = 0;
            E = 0;
			#5
			H = 1;
            G = 1;
            F = 0;
            E = 1;
    end

endmodule // coder_decoder_tf