

// TOOL:     vlog2tf
// DATE:     Tue Apr 29 19:49:18 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   demux_18
// DESIGN:   demux_18
// FILENAME: demux_18_tf.v
// PROJECT:  demux_18
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module demux_18_tf();

// Inputs
    reg in;
    reg [2:0] sel;


// Outputs
    wire [7:0] out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    demux_18 UUT (
        .in(in), 
        .sel(sel), 
        .out(out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            in = 1;
            sel = 3'b000;#10
            sel = 3'b001;#10
            sel = 3'b010;#10
            sel = 3'b011;#10
            sel = 3'b100;#10
            sel = 3'b101;#10
            sel = 3'b110;#10
            sel = 3'b111;
            
    end

endmodule // demux_18_tf