

// TOOL:     vlog2tf
// DATE:     Mon Apr 28 20:42:54 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   mux_161
// DESIGN:   mux_161
// FILENAME: mux_161_tf.v
// PROJECT:  mux_161
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module mux_161_tf();

// Inputs
    reg [15:0] D;
    reg [3:0] S;


// Outputs
    wire Y;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    mux_161 UUT (
        .D(D), 
        .S(S), 
        .Y(Y)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            D = 16'd16;
            S = 4'd0; #10
			S = 4'd2; #10
			S = 4'd4; #10
			S = 4'd6; #10
			S = 4'd8; #10
			D = 16'd50;
            S = 4'd10; #10
			S = 4'd12; #10
			S = 4'd14; #10
			S = 4'd3; #10
            S = 4'd5; #10
			D = 16'd10027;
            S = 4'd11; #10
			S = 4'd13; #10
			S = 4'd15;
    end

endmodule // mux_161_tf