

// TOOL:     vlog2tf
// DATE:     Thu Aug 14 20:57:16 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   kalman_fsm
// DESIGN:   kalman_fsm
// FILENAME: kalman_fsm_tf.v
// PROJECT:  kalman_core
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module kalman_fsm_tf();

// Inputs
    reg [15:0] theta_acc;
    reg [15:0] phi_acc;
    reg clk;
    reg reset;
    reg start;


// Outputs
    wire finish;
    wire [15:0] phi_est;
    wire [15:0] theta_est;
    wire [3:0] state;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    kalman_fsm UUT (
        .theta_acc(theta_acc), 
        .phi_acc(phi_acc), 
        .clk(clk), 
        .reset(reset), 
        .start(start), 
        .finish(finish), 
        .phi_est(phi_est), 
        .theta_est(theta_est), 
        .state(state)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            theta_acc = 0;
            phi_acc = 0;
            clk = 0;
            reset = 0;
            start = 0;
    end

endmodule // kalman_fsm_tf