

// TOOL:     vlog2tf
// DATE:     Fri May 23 20:06:05 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   mux_4
// DESIGN:   mux_4
// FILENAME: mux_4_tf.v
// PROJECT:  mux_14
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module mux_4_tf();

// Inputs
    reg [3:0] d0;
    reg [3:0] d1;
    reg [3:0] d2;
    reg [3:0] d3;
    reg [1:0] sel;


// Outputs
    wire [3:0] y;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    mux_4 UUT (
        .d0(d0), 
        .d1(d1), 
        .d2(d2), 
        .d3(d3), 
        .sel(sel), 
        .y(y)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            d0 = 1;
            d1 = 2;
            d2 = 3;
            d3 = 4;
            sel = 0;
			#10
            sel = 1;
			#10
            sel = 2;
			#10
            sel = 3;
			#10;
			sel = 2'bxx;
    end

endmodule // mux_4_tf