

// TOOL:     vlog2tf
// DATE:     Tue Apr 01 18:26:10 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   fourbit
// DESIGN:   fourbit
// FILENAME: fourbit_tf.v
// PROJECT:  fulladder
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module fourbit_tf();

// Inputs
    reg [3:0] a;
    reg [3:0] b;
    reg cin;


// Outputs
    wire [3:0] sum;
    wire carry;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    fourbit UUT (
        .a(a), 
        .b(b), 
        .cin(cin), 
        .sum(sum), 
        .carry(carry)
        );


// Initialize Inputs
// You can add your stimulus here
        initial begin
            a = 1;
            b = 1;
            cin = 0;
			#5
			a = 7;
			b = 4;
			cin = 1;
			#5
			a = 7;
			b = 4;
			cin = 1;
			#5
			a = 7;
			b = 7;
			cin = 1;
			#5
			a = 7;
			b = 9;
			cin = 0;
    end

endmodule // fourbit_tf