

// TOOL:     vlog2tf
// DATE:     Fri Mar 28 19:46:29 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   fulladd
// DESIGN:   fulladd
// FILENAME: fulladd_tf.v
// PROJECT:  fulladder
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module fulladd_tf();

// Inputs
    reg a;
    reg b;
    reg cin;


// Outputs
    wire sum;
    wire carry;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    fulladd UUT (
        .a(a), 
        .b(b), 
        .cin(cin), 
        .sum(sum), 
        .carry(carry)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            a = 1;
            b = 1;
            cin = 0;
			#5
			a = 0;
			b = 1;
			cin = 1;
			#5
			a = 0;
			b = 1;
			cin = 1;
    end

endmodule // fulladd_tf