

// TOOL:     vlog2tf
// DATE:     Tue May 13 14:18:44 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   ula_ula
// DESIGN:   ula_ula
// FILENAME: ula_ula_tf.v
// PROJECT:  aula24_ula
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module ula_ula_tf();

// Inputs
    reg [3:0] A;
    reg [3:0] B;
    reg [2:0] seletor;


// Outputs
    wire [3:0] resultado;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    ula_ula UUT (
        .A(A), 
        .B(B), 
        .seletor(seletor), 
        .resultado(resultado)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            A = 4'b0011;
            B = 4'b0100;
            seletor = 3'b000; #10;
			seletor = 3'b001; #10;
			seletor = 3'b010; #10;
			seletor = 3'b011; #10;
			seletor = 3'b100; #10;
			seletor = 3'b101; #10;
			seletor = 3'b110; #10;
    end

endmodule // ula_ula_tf