

// TOOL:     vlog2tf
// DATE:     Wed May 07 21:19:16 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   meio_subtrador_behav
// DESIGN:   meio_subtrador_behav
// FILENAME: meio_subtrador_behav_tf.v
// PROJECT:  aula22_subrator
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module meio_subtrador_behav_tf();

// Inputs
    reg A;
    reg B;


// Outputs
    wire D1;
    wire Br1;
	wire D2;
	wire Br2;
	wire D3;
	wire Br3;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    meio_subtrador_behav UUT (
        .A(A), 
        .B(B), 
        .D(D1), 
        .Br(Br1)
        );
	meio_subtrador_behavalt UUT2 (
        .A(A), 
        .B(B), 
        .D(D2), 
        .Br(Br2)
        );
	meio_subtrador_behav UUT3 (
        .A(A), 
        .B(B), 
        .D(D3), 
        .Br(Br3)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            A = 1'b0;
            B = 1'b0;
			#10;
			A = 1'b0;
            B = 1'b1;
			#10;
			A = 1'b1;
            B = 1'b0;
			#10;
			A = 1'b1;
            B = 1'b1;
    end

endmodule // meio_subtrador_behav_tf