

// TOOL:     vlog2tf
// DATE:     Tue Apr 29 21:58:46 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   logic_func_3bit
// DESIGN:   logic_func_3bit
// FILENAME: logic_func_3bit_tf.v
// PROJECT:  logic_func_3bits
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module logic_func_3bit_tf();

// Inputs
    reg A;
    reg B;
    reg C;


// Outputs
    wire F;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    logic_func_3bit UUT (
        .A(A), 
        .B(B), 
        .C(C), 
        .F(F)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            A = 0;
            B = 0;
            C = 0;#10
			A = 0;
            B = 0;
            C = 1;#10
			A = 0;
            B = 1;
            C = 0;#10
			A = 0;
            B = 1;
            C = 1;#10
			A = 1;
            B = 0;
            C = 0;#10
			A = 1;
            B = 0;
            C = 1;#10
			A = 1;
            B = 1;
            C = 0;#10
			A = 1;
            B = 1;
            C = 1;
			
    end

endmodule // logic_func_3bit_tf