

// TOOL:     vlog2tf
// DATE:     Thu Jun 26 23:24:01 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   arbiter
// DESIGN:   arbiter
// FILENAME: arbiter_tf.v
// PROJECT:  ARBITRER
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module arbiter_tf();

// Inputs
    reg [1:3] r;
    reg Resetn;
    reg Clock;


// Outputs
    wire [1:3] g;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    arbiter UUT (
        .r(r), 
        .Resetn(Resetn), 
        .Clock(Clock), 
        .g(g)
        );

// Clock stimulus generator

initial Clock = 0;
always #5 Clock = ~Clock; // Toggle clock every 5 time units (10 time unit period)


// Initialize Inputs
// You can add your stimulus here
    initial begin
            r = 3'b000;
            Resetn = 0;
            #5;
			Resetn =1;
			#5
			r= 3'b000; // idle
			#10
			r=3'b100; // gnt1
			#10;
			r=3'b001; // gnt3
			#10;
			r=3'b110; // gnt1
			#10;
			r=3'b001; // gnt3
			#10;
			r=3'b111; // gnt1
			#10;
			r=3'b000; // gnt 0
			#10;
			r=3'b010; // gnt 2 
			#10;
			r=3'b001; // gnt 3
 			#10;
			r=3'b011; // gnt 2
			#10;
			r=3'b000; // gnt 0
			#10;
			r=3'b010; // gnt  2
			#10;
			r=3'b001; // gnt 3
			#10;
			r=3'b111; // gnt 1
			#10;
			r=3'b000; // gnt 0
			#10;
    end

endmodule // arbiter_tf