

// TOOL:     vlog2tf
// DATE:     Wed Jun 18 21:54:52 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   serdes_receiver
// DESIGN:   serdes_receiver
// FILENAME: serdes_receiver_tf.v
// PROJECT:  aula_8b10b
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module serdes_receiver_tf();

// Inputs
    reg reset;
    reg clk;
    reg rx_in;


// Outputs
    wire [7:0] data_out;
    wire start_of_frame;
    wire code_err;
    wire disp_err;
    wire data_valid;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    serdes_receiver UUT (
        .reset(reset), 
        .clk(clk), 
        .rx_in(rx_in), 
        .data_out(data_out), 
        .start_of_frame(start_of_frame), 
        .code_err(code_err), 
        .disp_err(disp_err), 
        .data_valid(data_valid)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            reset = 0;
            clk = 0;
            rx_in = 0;
    end

endmodule // serdes_receiver_tf