

// TOOL:     vlog2tf
// DATE:     Tue Apr 29 20:54:28 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   demux_18
// DESIGN:   demux_18
// FILENAME: demux_18_tf.v
// PROJECT:  demux_18_214
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module demux_18_tf();

// Inputs
    reg in;
    reg [3:0] sel;


// Outputs
    wire [7:0] out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    demux_18 UUT (
        .in(in), 
        .sel(sel), 
        .out(out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            in = 0;
            sel = 0;#10
			in = 1;
			sel = 4'b0000;#10
			in = 1;
        sel = 4'b0011;
        #10
		 in = 1;
        sel = 4'b0100;
        #10
		in = 1;
        sel = 4'b0111;
        #10
		 in = 0;
        sel = 4'b0101;
        #10
		in = 1;
        sel = 4'b0001;
        #10
		sel = 4'b0110;
        #10;
    end

endmodule // demux_18_tf