

// TOOL:     vlog2tf
// DATE:     Wed May 14 11:35:36 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   datapath
// DESIGN:   datapath
// FILENAME: datapath_tf.v
// PROJECT:  aula26_datapath
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module datapath_tf();

// Inputs
    reg [3:0] dados;
    reg [1:0] addr;
    reg sel21;
    reg sel12;
    reg clk;
    reg escrita;
    reg reset;
    reg Cin;
    reg [2:0] operacao;


// Outputs
    wire [3:0] resultado;
    wire Cout;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    datapath UUT (
        .dados(dados), 
        .addr(addr), 
        .sel21(sel21), 
        .sel12(sel12), 
        .clk(clk), 
        .escrita(escrita), 
        .reset(reset), 
        .Cin(Cin), 
        .operacao(operacao), 
        .resultado(resultado), 
        .Cout(Cout)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            dados = 0;
            addr = 0;
            sel21 = 0;
            sel12 = 0;
            clk = 0;
            escrita = 0;
            reset = 1;
            Cin = 0;
            operacao = 3'b000;
    end

endmodule // datapath_tf