

// TOOL:     vlog2tf
// DATE:     Tue Apr 29 21:30:00 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   logic_sum
// DESIGN:   logic_sum
// FILENAME: logic_sum_tf.v
// PROJECT:  anbnpABn
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module logic_sum_tf();

// Inputs
    reg A;
    reg B;


// Outputs
    wire F;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    logic_sum UUT (
        .A(A), 
        .B(B), 
        .F(F)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            A = 1'b0;
            B = 1'b0;#10
			A = 1'b0;
            B = 1'b1;#10
			A = 1'b1;
            B = 1'b0;#10
			A = 1'b1;
            B = 1'b0;#10
			A = 1'b1;
            B = 1'b1;
    end

endmodule // logic_sum_tf