

// TOOL:     vlog2tf
// DATE:     Wed May 07 21:40:43 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   subtrador_completo_behav
// DESIGN:   subtrador_completo_behav
// FILENAME: subtrador_completo_behav_tf.v
// PROJECT:  aula22_subrator
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module subtrador_completo_behav_tf();

// Inputs
    reg A;
    reg B;
    reg Brin;


// Outputs
    wire D1;
    wire D2;
    wire D3;
    wire Brout1;
    wire Brout2;
    wire Brout3;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    subtrador_completo_behav UUT1 (
        .A(A), 
        .B(B), 
        .Brin(Brin), 
        .D(D1), 
        .Brout(Brout1)
        );
	subtrador_completo_behav UUT2 (
        .A(A), 
        .B(B), 
        .Brin(Brin), 
        .D(D2), 
        .Brout(Brout2)
        );
	subtrador_completo_behav UUT3 (
        .A(A), 
        .B(B), 
        .Brin(Brin), 
        .D(D3), 
        .Brout(Brout3)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            A = 0;
            B = 0;
            Brin = 0;
			#10
			A = 1;
            B = 0;
            Brin = 0;
			#10
			A = 0;
            B = 1;
            Brin = 0;
			#10
			A = 1;
            B = 1;
            Brin = 0;
			#10
			A = 0;
            B = 0;
            Brin = 1;
			#10
			A = 1;
            B = 0;
            Brin = 1;
			#10
			A = 0;
            B = 1;
            Brin = 1;
			#10
			A = 1;
            B = 1;
            Brin = 1;
    end

endmodule // subtrador_completo_behav_tf