

// TOOL:     vlog2tf
// DATE:     Thu May 29 21:12:34 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   main
// DESIGN:   main
// FILENAME: main_tf.v
// PROJECT:  aula7_pwm
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 us / 1 ps

// Define Module for Test Fixture
module main_tf();

// Inputs
    reg clk;
    reg reset;
    reg [1:0]duty_sel;


// Outputs
    wire pwm_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    main UUT (
        .clk(clk), 
        .reset(reset), 
        .duty_sel(duty_sel), 
        .pwm_out(pwm_out)
        );

// Clock Generation
initial clk = 0;
always #5 clk = ~clk; // 10 ms clock period



// Initialize Inputs
// You can add your stimulus here
    initial begin
            reset = 1;
            duty_sel = 0;
			#10;
			reset =0;
			#30000;
			duty_sel = 1;
			#30000;
			duty_sel =2;
			#30000;
			duty_sel = 3;
			#30000;	
    end

endmodule // main_tf