

// TOOL:     vlog2tf
// DATE:     Mon Jun 16 20:51:09 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   rw_16x8_sync
// DESIGN:   rw_16x8_sync
// FILENAME: rw_16x8_sync_tf.v
// PROJECT:  aula1_RAM_ROM
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module rw_16x8_sync_tf();

// Inputs
    reg [3:0] address;
    reg WE;
    reg [7:0] data_in;
    reg Clock;


// Outputs
    wire [7:0] data_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    rw_16x8_sync UUT (
        .data_out(data_out), 
        .address(address), 
        .WE(WE), 
        .data_in(data_in), 
        .Clock(Clock)
        );

always #5 Clock = ~Clock;

// Initialize Inputs
// You can add your stimulus here
    initial begin
            address = 0;
            WE = 0;
            data_in = 0;
            Clock = 0;
	// escrevendo valores
		#10 WE = 1; address = 4'b0001; data_in= 8'hAA;
		#10 WE = 1; address = 4'b0010; data_in = 8'hBB;
		#10 WE = 1; address = 4'b0011; data_in = 8'hCC;
		
	// desligando WE
		#10 WE = 0; address = 4'b0001;
		#10 address = 4'b0010;
		#10 address = 4'b0011;
		
		#10 $stop;
    end

endmodule // rw_16x8_sync_tf