

// TOOL:     vlog2tf
// DATE:     Fri Apr 04 20:13:52 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   debounce
// DESIGN:   debounce
// FILENAME: debounce_tf.v
// PROJECT:  debounce
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module debounce_tf();

// Inputs
    reg clk;
    reg rst;
    reg noisy_in;


// Outputs
    wire clean_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    debounce UUT (
        .clk(clk), 
        .rst(rst), 
        .noisy_in(noisy_in), 
        .clean_out(clean_out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            #5 clk =~ clk;
            #50 rst = 1;
			#60 rst = 0;
            #75 noisy_in = 1;
			#85 noisy_in = 0;
    end

endmodule // debounce_tf