

// TOOL:     vlog2tf
// DATE:     Thu May 29 21:21:41 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   pwm
// DESIGN:   pwm
// FILENAME: pwm_tf.v
// PROJECT:  aula7_pwm
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 us / 1 ps

// Define Module for Test Fixture
module pwm_tf();

// Inputs
    reg clk;
    reg reset;
    reg [1:0] duty;


// Outputs
    wire pwm_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    pwm UUT (
        .clk(clk), 
        .reset(reset), 
        .duty(duty), 
        .pwm_out(pwm_out)
        );
initial clk = 0;
always #5 clk = ~clk; // 10 ms clock period


// Initialize Inputs
// You can add your stimulus here
    initial begin
            clk = 0;
            reset = 1;
            duty = 0;
			#10;
			reset =0;
			#30000;
			duty = 1;
			#30000;
			duty =2;
			#30000;
			duty = 3;
			#30000;
    end

endmodule // pwm_tf