

// TOOL:     vlog2tf
// DATE:     Tue Apr 29 21:20:46 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   decod24
// DESIGN:   decod24
// FILENAME: decod24_tf.v
// PROJECT:  decodificador_fluxo
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module decod24_tf();

// Inputs
    reg A;
    reg B;


// Outputs
    wire Y0;
    wire Y1;
    wire Y2;
    wire Y3;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    decod24 UUT (
        .A(A), 
        .B(B), 
        .Y0(Y0), 
        .Y1(Y1), 
        .Y2(Y2), 
        .Y3(Y3)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            A = 1'b0;
            B = 1'b0;#10
			A = 1'b0;
            B = 1'b1;#10
			A = 1'b1;
            B = 1'b0;#10
			A = 1'b1;
            B = 1'b1;
    end

endmodule // decod24_tf