

// TOOL:     vlog2tf
// DATE:     Tue May 13 15:09:59 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   exula_ula
// DESIGN:   exula_ula
// FILENAME: aula25_ex_ula_tf.v
// PROJECT:  aula25_ex_ula
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module exula_ula_tf();

// Inputs
    reg [3:0] A;
    reg Cin;
    reg [3:0] B;
    reg [2:0] seletor;


// Outputs
    wire [3:0] resultado;
    wire Cout;
    wire Gout;
    wire Pout;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    exula_ula UUT (
        .A(A), 
        .Cin(Cin), 
        .B(B), 
        .seletor(seletor), 
        .resultado(resultado), 
        .Cout(Cout), 
        .Gout(Gout), 
        .Pout(Pout)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
           // Test cases focusing on sum operation
		   seletor = 3'b100;
    A = 4'b0000; B = 4'b0000; Cin = 0; #10;  // 0 + 0 = 0
    A = 4'b0001; B = 4'b0001; Cin = 0; #10;  // 1 + 1 = 2
    A = 4'b0010; B = 4'b0010; Cin = 1; #10;  // 2 + 2 + Cin(1) = 5
    A = 4'b0111; B = 4'b0001; Cin = 0; #10;  // 7 + 1 = 8 (Check Cout)
    A = 4'b1111; B = 4'b0001; Cin = 0; #10;  // 15 + 1 = 16 (Overflow case)
    A = 4'b1100; B = 4'b0100; Cin = 1; #10;  // 12 + 4 + 1 = 17 (Carry propagation)
    A = 4'b1010; B = 4'b0110; Cin = 1; #10;  // 10 + 6 + 1 = 17

    end

endmodule // exula_ula_tf