

// TOOL:     vlog2tf
// DATE:     Wed Jul 02 20:52:50 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   uart_tx
// DESIGN:   uart_tx
// FILENAME: uart_tx_tf.v
// PROJECT:  UART
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module uart_tx_tf();

// Inputs
    reg clk;
    reg reset;
    reg [7:0] data_in;
    reg tx_start;


// Outputs
    wire tx;
    wire tx_done;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    uart_tx UUT1 (
        .clk(clk), 
        .reset(reset), 
        .data_in(data_in), 
        .tx_start(tx_start), 
        .tx(tx), 
        .tx_done(tx_done)
        );
	    uart_rx UUT2 (
        .clk(clk), 
        .reset(reset), 
        .rx(tx), 
        .data_out(data_out), 
        .rx_done(rx_done)
        );



// Initialize Inputs
// You can add your stimulus here
    initial begin
            clk = 0;
            reset = 0;
            data_in = 0;
            tx_start = 0;
    end

endmodule // uart_tx_tf