

// TOOL:     vlog2tf
// DATE:     Wed Jul 02 20:54:43 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   uart_rx
// DESIGN:   uart_rx
// FILENAME: uart_rx_tf.v
// PROJECT:  UART
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module uart_rx_tf();

// Inputs
    reg clk;
    reg reset;
    reg rx;


// Outputs
    wire [7:0] data_out;
    wire rx_done;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    uart_rx UUT (
        .clk(clk), 
        .reset(reset), 
        .rx(rx), 
        .data_out(data_out), 
        .rx_done(rx_done)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            clk = 0;
            reset = 0;
            rx = 0;
    end

endmodule // uart_rx_tf