

// TOOL:     vlog2tf
// DATE:     Wed Apr 09 19:31:23 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   and_gate_primitives
// DESIGN:   and_gate_primitives
// FILENAME: and_gate_primitives_tf.v
// PROJECT:  transistors
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module and_gate_primitives_tf();

// Inputs
    reg a;
    reg b;


// Outputs
    wire s;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    and_gate_primitives UUT (
        .a(a), 
        .b(b), 
        .s(s)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            a = 0;
            b = 0;
			#20
			a = 1;
			b = 0;
			#20
			a = 0;
			b = 1;
			#20
			a = 1;
			b = 1;
    end

endmodule // and_gate_primitives_tf