

// TOOL:     vlog2tf
// DATE:     Tue Apr 08 19:07:22 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   my_design
// DESIGN:   my_design
// FILENAME: my_design_tf.v
// PROJECT:  for_generate
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module my_design_tf();

// Inputs
    reg [3:0] a;
    reg [3:0] b;


// Outputs
    wire [3:0] sum;
    wire [3:0] carry;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    my_design UUT (
        .a(a), 
        .b(b), 
        .sum(sum), 
        .carry(carry)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            a = 0;
            b = 0;
    end

endmodule // my_design_tf