

// TOOL:     vlog2tf
// DATE:     Tue Apr 08 19:42:00 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   my_design
// DESIGN:   my_design
// FILENAME: my_design_tf.v
// PROJECT:  for_generate
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module my_design_tf();

// Inputs
    reg [7:0] a;
    reg [7:0] b;
    reg cin;


// Outputs
    wire [7:0] sum;
    wire carry;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    my_design UUT (
        .a(a), 
        .b(b), 
        .cin(cin), 
        .sum(sum), 
        .carry(carry)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            a = 30;
            b = 230;
            cin = 0;
    end

endmodule // my_design_tf