

// TOOL:     vlog2tf
// DATE:     Fri Apr 25 21:52:25 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   cod164
// DESIGN:   cod164
// FILENAME: cod164_tf.v
// PROJECT:  cod_16_4_com_cod83
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module cod164_tf();

// Inputs
    reg [15:0] a_in;


// Outputs
    wire [3:0] a_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    cod164 UUT (
        .a_in(a_in), 
        .a_out(a_out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            
			a_in = 16'd0; #10;    // Expected: int_1 selected
        a_in = 16'd1; #10;  // Expected: int_1 selected
        a_in = 16'd2; #10;  // Expected: int_1 selected
        a_in = 16'd4; #10;  // Expected: int_2 selected
        a_in = 16'd8; #10;  // Expected: int_2 selected
        a_in = 16'd16; #10;
		a_in = 16'd32; #10;
		a_in = 16'd64; #10;
		a_in = 16'd128; #10;
		a_in = 16'd256; #10;
		a_in = 16'd512; #10;
		a_in = 16'd1024; #10;
		a_in = 16'd2048; #10;
		a_in = 16'd4096; #10;
		a_in = 16'd8192; #10;
    end

endmodule // cod164_tf