

// TOOL:     vlog2tf
// DATE:     Wed Jun 04 20:30:51 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   pwm
// DESIGN:   pwm
// FILENAME: pwm_tf.v
// PROJECT:  pwm
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module pwm_tf();

// Inputs
    reg [7:0] duty_cycle;
    reg clk;
    reg reset;


// Outputs
    wire pwm_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    pwm UUT (
        .duty_cycle(duty_cycle), 
        .clk(clk), 
        .reset(reset), 
        .pwm_out(pwm_out)
        );

initial begin
	clk=0;
	forever #5 clk = ~clk;
end

// Initialize Inputs
// You can add your stimulus here
    initial begin
			reset =1;
			#10
            duty_cycle = 127;
            reset = 0;
    end

endmodule // pwm_tf