

// TOOL:     vlog2tf
// DATE:     Thu Apr 24 21:14:30 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   comparator_comportamental
// DESIGN:   comparator_comportamental
// FILENAME: comparator_comportamental_tf.v
// PROJECT:  comparator_2bits
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 10 ns / 1 ps

// Define Module for Test Fixture
module comparator_comportamental_tf();

// Inputs
    reg [1:0] a;
    reg [1:0] b;


// Outputs
    wire y;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    comparator_comportamental UUT (
        .a(a), 
        .b(b), 
        .y(y)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            a = "00";
            b = "01";
			#5
			a = "11";
			b = "01";
			#5 
			a = "11";
			b = "11";
			#5
			b = "00";
			a = "11";
			#5
			a = "10";
			b = "11";
			#5
			a = "11";
			b = "11";
    end

endmodule // comparator_comportamental_tf