

// TOOL:     vlog2tf
// DATE:     Mon Apr 28 19:36:51 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   decoder_4_16
// DESIGN:   decoder_4_16
// FILENAME: decoder_4_16_tf.v
// PROJECT:  decod_416
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module decoder_4_16_tf();

// Inputs
    reg [3:0] a_in;


// Outputs
    wire [15:0] a_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    decoder_4_16 UUT (
        .a_in(a_in), 
        .a_out(a_out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            a_in = 4'd0; #10
			a_in = 4'd1; #10
			a_in = 4'd2; #10
			a_in = 4'd3; #10
			a_in = 4'd4; #10
			a_in = 4'd5; #10
			a_in = 4'd6; #10
			a_in = 4'd7; #10
			a_in = 4'd8; #10
			a_in = 4'd9; #10
			a_in = 4'd10; #10
			a_in = 4'd11; #10
			a_in = 4'd12; #10
			a_in = 4'd13; #10
			a_in = 4'd14; #10
			a_in = 4'd15;
    end

endmodule // decoder_4_16_tf