

// TOOL:     vlog2tf
// DATE:     Tue May 13 15:43:56 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   exula_8bits
// DESIGN:   exula_8bits
// FILENAME: aula25_ex_ula_tf.v
// PROJECT:  aula25_ex_ula
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module exula_8bits_tf();

// Inputs
    reg [7:0] A;
    reg Cin;
    reg [7:0] B;
    reg [2:0] seletor;


// Outputs
    wire [7:0] resultado;
    wire Cout;
    wire [1:0] Gout;
    wire [1:0] Pout;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    exula_8bits UUT (
        .A(A), 
        .Cin(Cin), 
        .B(B), 
        .seletor(seletor), 
        .resultado(resultado), 
        .Cout(Cout), 
        .Gout(Gout), 
        .Pout(Pout)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            // Apply test cases
        A = 8'b00000000; B = 8'b00000000; Cin = 0; seletor = 3'b100; #10; // Simple sum
        A = 8'b00000001; B = 8'b00000001; Cin = 0; seletor = 3'b100; #10; // Sum with carry propagation
        A = 8'b00001111; B = 8'b00000001; Cin = 0; seletor = 3'b100; #10; // Sum causing overflow in lower bits
        A = 8'b11111111; B = 8'b00000001; Cin = 0; seletor = 3'b100; #10; // Sum causing upper-bit overflow
        A = 8'b01010101; B = 8'b10101010; Cin = 1; seletor = 3'b100; #10; // Carry propagation test
        A = 8'b00110011; B = 8'b11001100; Cin = 0; seletor = 3'b000; #10; // AND operation
        A = 8'b10101010; B = 8'b01010101; Cin = 0; seletor = 3'b001; #10; // OR operation
       
    end

endmodule // exula_8bits_tf