

// TOOL:     vlog2tf
// DATE:     Tue May 20 19:37:10 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   wallace_estrutural
// DESIGN:   wallace_estrutural
// FILENAME: wallace_estrutural_tf.v
// PROJECT:  mult_wallace
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module wallace_estrutural_tf();

// Inputs
    reg [3:0] A;
    reg [3:0] B;


// Outputs
    wire [7:0] Produto;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    wallace_estrutural UUT (
        .A(A), 
        .B(B), 
        .Produto(Produto)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            A = 4'b1111;
            B = 4'b0000;
			#10; // 0
            A = 4'b0111;
            B = 4'b0010;
			#10; // 12x 1 = 12
			A = 4'b1110;
            B = 4'b0001;
			#10;// 15 x 5 = 75
			A = 4'b1111;
            B = 4'b0101;
			#10; 
			A = 4'b0011;
            B = 4'b0011;
			#10
			A = 4'b1111;
			B = 4'b1111;
			end

endmodule // wallace_estrutural_tf