

// TOOL:     vlog2tf
// DATE:     Mon Apr 07 19:25:13 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   reset_sinc
// DESIGN:   reset_sinc
// FILENAME: reset_sinc_tf.v
// PROJECT:  reset_sinc
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module reset_sinc_tf();

// Inputs
    reg clk_A;
    reg nrst_in;


// Outputs
    wire Q_nrst;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    reset_sinc UUT (
        .clk_A(clk_A), 
        .nrst_in(nrst_in), 
        .Q_nrst(Q_nrst)
        );


// Initialize Inputs
// You can add your stimulus here
     initial begin
    clk_A = 0;
    forever #5 clk_A = ~clk_A; // 5 time units for clock period
  end
 initial begin
    //$monitor("Time: %0t | Reset: %b | Outputs: %b", $time, reset, q);

    nrst_in = 1; // Apply reset
    #30; // Wait for 10 time units
    nrst_in = 0; // Remove reset
    #2; // Wait for some time to observe outputs

   // $finish; // End simulation
  end
endmodule