

// TOOL:     vlog2tf
// DATE:     Wed Apr 09 19:12:43 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   not_switch
// DESIGN:   not_switch
// FILENAME: not_switch_tf.v
// PROJECT:  transistors
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module not_switch_tf();

// Inputs
    reg a;


// Outputs
    wire s;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    not_switch UUT (
        .a(a), 
        .s(s)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            a = 0;
			#10
			a = 1;
    end

endmodule // not_switch_tf