

// TOOL:     vlog2tf
// DATE:     Wed May 14 11:35:36 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   datapath
// DESIGN:   datapath
// FILENAME: datapath_tf.v
// PROJECT:  aula26_datapath
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module datapath_tf();

// Inputs
    reg [3:0] dados;
    reg [1:0] addr;
    reg sel21;
    reg sel12;
    reg clk;
    reg escrita;
    reg reset;
    reg Cin;
    reg [2:0] operacao;


// Outputs
    wire [3:0] resultado;
    wire Cout;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    datapath UUT (
        .dados(dados), 
        .addr(addr), 
        .sel21(sel21), 
        .sel12(sel12), 
        .clk(clk), 
        .escrita(escrita), 
        .reset(reset), 
        .Cin(Cin), 
        .operacao(operacao), 
        .resultado(resultado), 
        .Cout(Cout)
        );

// Clock Generation (Period: 10ns)
always #5 clk = ~clk;


// Initialize Inputs
// You can add your stimulus here
    initial begin
            dados = 0;
            addr = 0;
            sel21 = 0;
            sel12 = 0;
            clk = 0;
            escrita = 0;
            reset = 1;
            Cin = 0;
            operacao = 3'b000; 
			#10;
			//inicializacao
			
			//escreve dados em rf[0] = 0111;
			dados = 4'b0111;
			addr = 2'b00;
			escrita = 1'b1;
			#10;
			
			escrita = 1'b0;
			#10;
			
			//escreve dados em rf[1] = 0011;
			dados = 4'b0011;
			addr = 2'b01;
			escrita = 1'b1;
			sel12 = 1'b1;
			#10;
			
			// operacao de soma;
			operacao= 3'b100;
			#10;
			
			//registro em rf[1];
			sel21 = 1'b1;
			escrita= 1'b1;
			addr = 2'b01;
			#10;
			// escrita e seletora estado normal sem registro
			sel21 = 1'b0;
			escrita= 1'b0;
			// endereco rf[2]
			addr = 2'b10;
			#10;
			// operacao sub 101
			operacao = 3'b101;
			
			//seleciono a saida
			#10
			sel21= 1'b1;
			// escrevo em rf2;
			#10
			escrita = 1'b1;
			#10
			escrita = 1'b0;
			// endereco rf[3]
			addr = 2'b11;
			operacao= 3'b110;
			#10
			//escolho registro da ula
			sel21 = 1'b1;
			#10
			//escrevo resultado da ula
			escrita = 1'b1;
			#10;
			
    end

endmodule // datapath_tf